ci(rpm): 添加 RPM 包上传步骤

diff --git a/.github/workflows/package-apisix-rpm-el7.yml b/.github/workflows/package-apisix-rpm-el7.yml
--- a/.github/workflows/package-apisix-rpm-el7.yml
+++ b/.github/workflows/package-apisix-rpm-el7.yml
@@ -2,13 +2,13 @@ name: package apisix rpm for el7
 
 on:
   push:
-    branches: [ master, apisix_3.8.1_runtime_1.1.1 ]
+    branches: [ master, htaizq_* ]
     tags:
       - "v*"
     paths-ignore:
       - '*.md'
   pull_request:
-    branches: [ master, apisix_3.8.1_runtime_1.1.1 ]
+    branches: [ master, htaizq_* ]
     paths-ignore:
       - '*.md'
   schedule:
@@ -18,7 +18,7 @@ on:
       apisix_version:
         description: 'APISIX version to package'
         required: false
-        default: 'htaizq/3.8.1'
+        default: ''
         type: string
 
 jobs:
@@ -26,7 +26,7 @@ jobs:
     runs-on: ubuntu-latest
     timeout-minutes: 60
     env:
-      APISIX_VERSION: ${{ github.event.inputs.apisix_version || 'htaizq/3.8.1' }}
+      APISIX_VERSION: ${{ github.event.inputs.apisix_version || github.ref_name }}
 #    services:
 #      etcd:
 #        image: quay.io/coreos/etcd:v3.5.9
@@ -61,11 +61,11 @@ jobs:
           wget https://raw.githubusercontent.com/xuzhijvn/apisix/${APISIX_VERSION}/.requirements && source .requirements
           make package type=rpm app=apisix version=master checkout=${APISIX_VERSION} runtime_version=${APISIX_RUNTIME} image_base=centos image_tag=7 artifact=apisix-remote
 
-      - name: packaging APISIX(-local) with local code
-        run: |
-          wget https://raw.githubusercontent.com/xuzhijvn/apisix/${APISIX_VERSION}/.requirements && source .requirements
-          git clone -b ${APISIX_VERSION} https://github.com/xuzhijvn/apisix.git
-          make package type=rpm app=apisix version=master checkout=${APISIX_VERSION} runtime_version=${APISIX_RUNTIME} image_base=centos image_tag=7 local_code_path=./apisix artifact=apisix-local
+#      - name: packaging APISIX(-local) with local code
+#        run: |
+#          wget https://raw.githubusercontent.com/xuzhijvn/apisix/${APISIX_VERSION}/.requirements && source .requirements
+#          git clone -b ${APISIX_VERSION} https://github.com/xuzhijvn/apisix.git
+#          make package type=rpm app=apisix version=master checkout=${APISIX_VERSION} runtime_version=${APISIX_RUNTIME} image_base=centos image_tag=7 local_code_path=./apisix artifact=apisix-local
 
       - name: run centos7 docker and mapping rpm into container
         run: |
@@ -103,15 +103,38 @@ jobs:
           docker exec centos7Instance bash -c "pkill -f nginx"
           docker exec centos7Instance bash -c "yum -y erase apisix-remote-master"
 
-      - name: install APISIX(-local) by rpm in container
-        run: |
-          docker exec centos7Instance bash -c "yum -y localinstall /output/apisix-local-master-0.el7.x86_64.rpm"
-          docker exec centos7Instance bash -c "apisix start"
+#      - name: install APISIX(-local) by rpm in container
+#        run: |
+#          docker exec centos7Instance bash -c "yum -y localinstall /output/apisix-local-master-0.el7.x86_64.rpm"
+#          docker exec centos7Instance bash -c "apisix start"
 
-      - name: check and ensure APISIX(-local) is installed
+#      - name: check and ensure APISIX(-local) is installed
+#        run: |
+#          code=$(curl -k -i -m 20 -o /dev/null -s -w %{http_code} http://127.0.0.1:9180/apisix/admin/routes -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1')
+#          if [ ! $code -eq 200 ]; then
+#              echo "failed: failed to install Apache APISIX by rpm"
+#              exit 1
+#          fi
+
+      - name: install yumdownloader tools inside centos7 container
         run: |
-          code=$(curl -k -i -m 20 -o /dev/null -s -w %{http_code} http://127.0.0.1:9180/apisix/admin/routes -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1')
-          if [ ! $code -eq 200 ]; then
-              echo "failed: failed to install Apache APISIX by rpm"
-              exit 1
-          fi
+          docker exec centos7Instance bash -c "yum install -y yum-utils"
+
+      - name: download offline dependencies
+        run: |
+          docker exec centos7Instance bash -c "\
+            mkdir -p /output/deps \
+            && yumdownloader --resolve --destdir=/output/deps /output/apisix-remote-master-0.el7.x86_64.rpm || true \
+          "    
+
+      - name: archive offline installation package
+        run: |
+          TAR_NAME="api6_${APISIX_VERSION}-0_el7.x86_64.tar.gz"
+          tar -czvf $TAR_NAME output/
+          echo "TAR_NAME=$TAR_NAME" >> $GITHUB_ENV
+
+      - name: upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.TAR_NAME }}
+          path: ${{ env.TAR_NAME }}
